#set srcdir "/remote/arctools/akolesov/gnu_nightly_tlsdev/default/gcc/gcc/testsuite"
#set arc_exec_prefix "/slowfs/us01dwslow025/akolesov/gnu_nightly_tlsdev/builds/4/arc-archs-linux-gnu/bin/arc-linux"

#set arc_exec_prefix "$env(INSTALL_DIR)/bin/arc-snps-linux-uclibc"
set srcdir "$env(SOURCE_DIR)/gcc/gcc/testsuite"
set arc_exec_prefix "$env(INSTALL_DIR)/bin/arc-snps-linux-gnu"
#set arc_exec_prefix "/home/cmiranda/buildroot/linux_alexey_failing_to_boot/output/host/usr/bin/arc-buildroot-linux-uclibc"

set target_alias    "arc-linux-gnu"
set target_triplet  "arc-archs-linux-gnu"
set rootme	    "."
set tmpdir	    "/SCRATCH/akolesov/jenkins_root/linux-arctest3/workspace/gnu_linux_dejagnu_tlsdev/TA_DEJAGNU_TOOL/gcc/TA_TARGET_CONFIG/arc-archs-linux-gnu/label/linux-test-executor/_tmp"
set CFLAGS	    ""
set CXXFLAGS	    ""
set SIM		    "${arc_exec_prefix}-run"
set GDB		    "${arc_exec_prefix}-gdb"
# Binutils
set NM		    "${arc_exec_prefix}-nm"
set SIZE	    "${arc_exec_prefix}-size"
set OBJDUMP	    "${arc_exec_prefix}-objdump"
set OBJCOPY	    "${arc_exec_prefix}-objcopy"
set AR		    "${arc_exec_prefix}-ar"
set STRIP	    "${arc_exec_prefix}-strip"
set READELF	    "${arc_exec_prefix}-readelf"
set ELFEDIT	    "${arc_exec_prefix}-elfedit"
# ld
set LD		    "${arc_exec_prefix}-ld"

#set verbose 9

set tool gcc
#set tool g++

if { $tool == "gcc" || $tool == "g++" } {
    set GCC_UNDER_TEST  "${arc_exec_prefix}-gcc"
    set GXX_UNDER_TEST  "${arc_exec_prefix}-g++"
} else {
    set CC_FOR_TARGET   "${arc_exec_prefix}-gcc"
    set CC		"${arc_exec_prefix}-gcc"
    set CXX_FOR_TARGET  "${arc_exec_prefix}-g++"
    set CXX		"${arc_exec_prefix}-g++"
}

switch $tool {
    libstdc++ {
	set baseline_subdir_switch "--print-multi-directory"
    }
    gdb {
	source $srcdir/lib/append_gdb_boards_dir.exp
	if {[string match arc*-linux-gnu $target_triplet]} {
	    set gdb_server_prog "/usr/bin/gdbserver"
	    set toolchain_sysroot_dir "/slowfs/us01dwslow025/akolesov/gnu_nightly_tlsdev/builds/4/arc-archs-linux-gnu/arc-snps-linux-gnu/sysroot"
	}
    }
}

set target_triplet arc-unknown-linux-gnu
set target_alias arc-snps-linux-gnu
set target_board arc-linux-gnu
set target_list arc-linux-aa4

#set verbose 2
